# Generated by Django 2.2.13 on 2021-08-28 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0002_chattracker_income'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chattracker',
            name='iehBool',
            field=models.BooleanField(default=True),
        ),
    ]
