# Generated by Django 3.2.4 on 2021-07-19 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0020_auto_20210629_2139'),
    ]

    operations = [
        migrations.AddField(
            model_name='chattracker',
            name='ReservationClientCode',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='chattracker',
            name='ReservationUserCode',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='chattracker',
            name='ReservationVendorCode',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='chattracker',
            name='TribalEligible',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='chattracker',
            name='flowchart3_status',
            field=models.BooleanField(default=False),
        ),
    ]
