# Generated by Django 3.2.4 on 2021-07-19 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0021_auto_20210719_1144'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chattracker',
            old_name='flowchart3_status',
            new_name='flowchart3_stucked_status',
        ),
    ]
