# Generated by Django 3.2.4 on 2021-07-19 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0022_rename_flowchart3_status_chattracker_flowchart3_stucked_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='chattracker',
            name='apt_unit',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='chattracker',
            name='date',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='chattracker',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='chattracker',
            name='form_zip_code',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='chattracker',
            name='is_permanent',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='chattracker',
            name='last_four_social',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='chattracker',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='chattracker',
            name='middle_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='chattracker',
            name='program',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='chattracker',
            name='residential_address',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='chattracker',
            name='second_last_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='chattracker',
            name='shipping_address',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='chattracker',
            name='suffix',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
