# Generated by Django 3.2.4 on 2021-07-19 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0023_auto_20210719_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='chattracker',
            name='form_filled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chattracker',
            name='residency_nature',
            field=models.BooleanField(default=True),
        ),
    ]
