# Generated by Django 3.2.4 on 2021-07-19 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0024_auto_20210719_2205'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chattracker',
            old_name='apt_unit',
            new_name='apt_unit1',
        ),
        migrations.AddField(
            model_name='chattracker',
            name='apt_unit2',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
