# Generated by Django 3.2.4 on 2021-07-19 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0026_alter_chattracker_residency_nature'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chattracker',
            old_name='residency_nature',
            new_name='address_nature',
        ),
    ]
