# Generated by Django 2.2.13 on 2021-07-20 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0027_rename_residency_nature_chattracker_address_nature'),
        ('root', '0021_startorder_userconfiguration'),
    ]

    operations = [
    ]
