# Generated by Django 2.2.13 on 2021-07-22 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0030_auto_20210721_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='chattracker',
            name='State',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
