# Generated by Django 2.2.13 on 2021-07-22 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0031_chattracker_state'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chattracker',
            old_name='State',
            new_name='ResidenceCity',
        ),
        migrations.RenameField(
            model_name='chattracker',
            old_name='zipcode',
            new_name='ResidenceZip',
        ),
        migrations.AddField(
            model_name='chattracker',
            name='ResidenceState',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='chattracker',
            name='TribalResident',
            field=models.BooleanField(default=False),
        ),
    ]
