# Generated by Django 2.2.13 on 2021-07-23 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0032_auto_20210722_2344'),
    ]

    operations = [
        migrations.AddField(
            model_name='chattracker',
            name='EligibiltyPrograms',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
