# Generated by Django 2.2.13 on 2021-07-29 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0034_chattracker_variable_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='chattracker',
            name='iehBool',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chattracker',
            name='islifeline_service',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='chattracker',
            name='other_adult',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='chattracker',
            name='share_liveing_expesses',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
