# Generated by Django 2.2.13 on 2021-07-31 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0039_auto_20210730_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='chattracker',
            name='BestWayToReachYou',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='chattracker',
            name='PhPinCodeoneNumber',
            field=models.CharField(blank=True, default='', max_length=4),
        ),
        migrations.AddField(
            model_name='chattracker',
            name='PhoneNumber',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
