# Generated by Django 2.2.13 on 2021-08-05 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0041_auto_20210803_0200'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chattracker',
            old_name='PhPinCodeoneNumber',
            new_name='PinCode',
        ),
        migrations.AddField(
            model_name='chattracker',
            name='ServicePlan',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
